services:
  ysss:
    restart: always
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    command: uv run ./главный.py